### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by tmytng** [tmytng/fleamarket_sample_80b#96]
## ■ URL
IPアドレス：http://18.178.50.19/
Github（最終課題のリポジトリ）：https://github.com/tmytng/fleamarket_sample_80b/

## ■ Basic認証
ID：marunouchi80
Pass：marunouchib

## ■ テスト用アカウント
◯ 購入者用
メールアドレス：sample1@test.com
パスワード：12345678

◯ 購入用カード情報
番号：4242424242424242
期限：01/22
セキュリティカード：123

◯ 出品者用
メールアドレス：test30@test.com
パスワード：12345678

**Comment by oooooooba** [comment]
tmytng さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・商品出品後に、出品された商品が出品一覧に表示されない
・出品内容・販売価格が適切である（著作権に反する画像を使用している可能性がある）
フリマアプリは企業に提出するので、新垣結衣の写真やagateなどの既存ブランド名は使わないようにしましょう




修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by oooooooba** [comment]
tmytng さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
"必須項目を入力した上で出品ができる。
必須項目が一つでも欠けていると商品出品ができない。
■必須項目
・画像
・商品名
・商品の説明
・カテゴリー
・商品の状態
・配送料の負担
・発送元地域
・発送までの日数
・価格の情報

商品の状態を選択せずに出品ができました。（商品の状態が「---」で登録できてしまっているようです。）
他項目も念のため確認してから提出をお願い致します。


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by rikuan** [comment]
上記修正しました！

**Comment by tmytng** [comment]
> tmytng さん、ご提出ありがとうございます！
> 挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
> 
> [修正箇所]
> ・商品出品後に、出品された商品が出品一覧に表示されない
> ・出品内容・販売価格が不適切である（著作権に反する画像を使用している可能性がある等）
> フリマアプリは企業に提出するので、新垣結衣の写真やagateなどの既存ブランド名は使わないようにしましょう
> 
> 修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
> https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

ご確認ありがとうございます。
本件修正いたしました。

**Comment by oooooooba** [comment]
> 「必須」と表現してあるカラムが空のときにユーザー登録ができない
> 「必須」と表現していないカラムが空のときにはユーザー登録ができる
→ユーザー新規登録の「自己紹介」欄が未入力でも登録できました。
　自己紹介はBチーム独自のものかと存じますので、必須にするかしないかは自由です。

・挙動確認をしていたところ、突然アプリが開けなくなり、下記文言が表示されました
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by rikuan** [comment]
修正しました！自己紹介は元々バリデーションかけておりませんので間違ってついておりました。必須を外しております。
挙動確認時にエラーとなったとのことでしたが、投稿された商品に何らかのエラーがあったようだったので投稿されていたテックブックという商品を一旦削除しております。可能であれば同じ状況になった時の状況をご教授いただければ幸いです。
その他こまごまと修正も行っております。（編集で画像削除ができなかったので修正）

**Comment by rumaruma0408** [comment]
rikuanさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

> 可能であれば同じ状況になった時の状況をご教授いただければ幸いです。


昨日のエラーですが、現在確認したところエラーは表示されませんでしたの問題ございません。昨日は以下画像の様なエラーが表示されました。
https://i.gyazo.com/dc9d363d94f584a832acc3fcd360defb.png

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
